[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --basetemp=../../.test-state/pytest-tmp
cache_dir = ../../.test-state/pytest-cache
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
